import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

interface LanguageContextType {
  language: 'en' | 'es';
  setLanguage: (lang: 'en' | 'es') => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.back': 'Back',
    'common.continue': 'Continue',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.optional': 'Optional',
    'common.required': 'Required',
    'common.yes': 'Yes',
    'common.no': 'No',
    
    // Navigation
    'nav.home': 'Home',
    'nav.grab': 'Grab',
    'nav.order': 'Order',
    'nav.profile': 'Profile',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to the free market. You can participate in',
    'dashboard.portfolioBalance': 'The balance of my portfolio',
    'dashboard.yesterday': 'Yesterday',
    'dashboard.accumulated': 'Accumulated',
    'dashboard.today': 'Today',
    'dashboard.deposit': 'Deposit',
    'dashboard.withdrawal': 'Withdrawal',
    
    // Orders
    'orders.title': 'List of tasks',
    'orders.inProgress': 'Order in progress',
    'orders.completed': 'Completed',
    'orders.frozen': 'Freeze',
    'orders.currentBalance': 'Current Balance',
    'orders.orderValue': 'Order value:',
    'orders.commission': 'Commission:',
    'orders.submitOrder': 'Submit Order',
    'orders.topUpRequired': 'Top-up Required',
    'orders.insufficientBalance': 'Insufficient Balance',
    'orders.needMoreFunds': 'You need {amount} more to submit this order.',
    'orders.orderAmount': 'Order Amount:',
    'orders.requiredTopUp': 'Required Top-up:',
    'orders.addFunds': 'Need to add funds?',
    'orders.goToDeposit': 'Go to Deposit Page',
    'orders.orderCompleted': 'Order Completed Successfully',
    'orders.orderCancelled': 'Order Cancelled',
    'orders.noPendingOrders': 'No pending orders',
    'orders.noCompletedOrders': 'No completed orders yet',
    'orders.noCancelledOrders': 'No cancelled orders',
    'orders.realTimeUpdates': 'Real-time order updates',
    'orders.submitting': 'Submitting...',
    'orders.time': 'Time:',
    'orders.orderCode': 'Order code:',
    'orders.nextOrder': 'Next Order',
    'orders.orderOf': 'Order {current} of {total}',
    'orders.allOrdersCompleted': 'All orders completed!',
    'orders.noOrdersAvailable': 'No orders available',
    'orders.withdrawalLocked': 'Complete all orders to unlock withdrawals',
    'orders.withdrawalUnlocked': 'Withdrawals are now available!',
    'orders.firstOrderRequired': 'Complete your first order to unlock withdrawals',
    'orders.orderProgress': 'Order Progress',
    'orders.currentBalance': 'Current Balance',
    'orders.todaysIncome': 'Today\'s income',
    'orders.completed': 'Completed',
    'orders.pending': 'Pending',
    'orders.ordersCompleted': 'Orders completed',
    'orders.ordersPending': 'Orders pending',
    'orders.realTimeOrderUpdates': 'Real-time order updates',
    'orders.noOrdersAvailable': 'No Orders Available',
    'orders.orderValue': 'Order value',
    'orders.commission': 'Commission',
    'orders.entryLevelPackage': 'Entry level package equal to user balance',
    'orders.realTimeBalance': 'Live',
    'orders.previousBalance': 'Previous Balance',
    'orders.newBalance': 'New Balance',
    
    // Profile
    'orders.ordersCompleted': 'Orders completed',
    'orders.ordersPending': 'Orders pending',
    'orders.completeFirstOrderToUnlock': 'Complete your first order to unlock withdrawals',
    
    // Profile
    'profile.title': 'Profile',
    'profile.balance': 'The balance of my portfolio:',
    'profile.withdrawal': 'Withdrawal',
    'profile.accounting': 'Accounting details',
    'profile.deposits': 'Deposit records',
    'profile.withdrawals': 'Withdrawal records',
    'profile.about': 'About us',
    'profile.invite': 'Invite friends',
    'profile.signOut': 'Sign Out',
    'profile.editProfile': 'Edit Profile',
    'profile.changePassword': 'Change Password',
    'profile.bankAccount': 'Bank Account',
    'profile.language': 'Language',
    'profile.accountInfo': 'Account Information',
    'profile.username': 'Username',
    'profile.country': 'Country',
    'profile.currency': 'Currency',
    'profile.vipStatus': 'VIP Status',
    'profile.vipMember': 'VIP Member',
    'profile.regularMember': 'Regular Member',
    
    // Authentication
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.createAccount': 'Create Account',
    'auth.welcomeBack': 'Welcome back!',
    'auth.joinPlatform': 'Join our financial platform',
    'auth.phoneNumber': 'Phone Number',
    'auth.password': 'Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.inviteCode': 'Invitation Code',
    'auth.processing': 'Processing...',
    'auth.accountPreview': 'Account Preview',
    'auth.name': 'Name',
    'auth.quickRegistration': 'Quick Registration',
    'auth.namesOptional': 'Names are optional and will be auto-generated if not provided!',
    'auth.inviteCodeRequired': 'Required: Enter a friend\'s invitation code to create your account',
    'auth.invalidInviteCode': 'Invalid invitation code. Please check and try again.',
    'auth.validInviteCode': 'Valid invitation code from user:',
    'auth.inviteRequired': 'Invitation Required',
    'auth.inviteRequiredDesc': 'You need a valid invitation code from an existing user to join!',
    'auth.createAccountPrompt': 'Don\'t have an account? Sign up now!',
    
    // Deposit
    'deposit.title': 'Deposit Funds',
    'deposit.currentBalance': 'Current Balance',
    'deposit.amount': 'Deposit Amount',
    'deposit.selectBank': 'Select Bank',
    'deposit.accountName': 'Account Name',
    'deposit.accountNumber': 'Account Number',
    'deposit.senderInfo': 'Your Account Information',
    'deposit.uploadProof': 'Upload Transfer Receipt',
    'deposit.submit': 'Submit Deposit Request',
    'deposit.success': 'Deposit Request Submitted!',
    'deposit.selectCountry': 'Select Country',
    'deposit.transferToAccount': 'Transfer to this account',
    'deposit.bank': 'Bank',
    'deposit.chooseImage': 'Choose Image',
    'deposit.removeImage': 'Remove Image',
    'deposit.uploadReceipt': 'Upload transfer receipt',
    'deposit.depositAmount': 'Deposit Amount',
    'deposit.currency': 'Currency',
    'deposit.yourAccountInfo': 'Your Account Information',
    'deposit.uploadTransferProof': 'Upload Transfer Proof',
    'deposit.uploadTransferReceipt': 'Upload transfer receipt',
    'deposit.chooseImage': 'Choose Image',
    'deposit.submitDepositRequest': 'Submit Deposit Request',
    'deposit.selectCountry': 'Select Country',
    'deposit.selectBank': 'Select Bank',
    'deposit.noBanksAvailable': 'No banks available for {country}',
    'deposit.currency': 'Currency: {currency} ({symbol})',
    
    // Withdrawal
    'withdrawal.title': 'Withdraw Funds',
    'withdrawal.amount': 'Withdrawal Amount',
    'withdrawal.method': 'Withdrawal Method',
    'withdrawal.availableBalance': 'Available Balance',
    'withdrawal.accountDetails': 'Account Details',
    'withdrawal.minimumWithdrawal': 'Minimum withdrawal',
    'withdrawal.verifyPassword': 'Verify Password',
    'withdrawal.enterPasswordToWithdraw': 'Please enter your login password to proceed with withdrawal',
    'withdrawal.withdrawalMethod': 'Withdrawal Method',
    'withdrawal.addNewAccount': 'Add New Account',
    'withdrawal.selectFromSavedAccounts': 'Select from your saved accounts:',
    'withdrawal.useSavedAccount': 'Use Saved Account',
    'withdrawal.addNewAccount': 'Add New Account',
    'withdrawal.minimumWithdrawalAmount': 'Minimum withdrawal: {symbol}10.00',
    'withdrawal.currency': 'Currency: {currency}',
    'withdrawal.withdraw': 'Withdraw {symbol}{amount}',
    'withdrawal.selectCountry': 'Select Country',
    'withdrawal.selectBank': 'Select Bank',
    'withdrawal.noBanksAvailable': 'No banks available for {country}',
    'withdrawal.withdrawalAmount': 'Withdrawal Amount ({currency})',
    'withdrawal.accountDetails': 'Account Details',
    'withdrawal.accountHolderName': 'Account Holder Name',
    'withdrawal.accountNumber': 'Account Number',
    'withdrawal.minimumAmount': 'Minimum: {symbol}10.00 | Currency: {currency}',
    
    // Available Balance
    'withdrawal.availableBalance': 'Available Balance',
    
    // General
    'general.save': 'Save',
    'general.cancel': 'Cancel',
    'general.back': 'Back',
    'general.loading': 'Loading...',
    'general.error': 'Error',
    'general.success': 'Success',
    'general.optional': 'Optional',
    'general.required': 'Required',
    'general.continue': 'Continue',
    
    // Hall of Fame
    'hallOfFame.title': 'Hall of Fame',
    'hallOfFame.liveUpdates': 'Live Updates',
    
    // VIP Status
    'vip.status': 'VIP Status',
    'vip.membershipLevel': 'Membership Level',
    'vip.live': 'Live',
    'vip.verified': 'Verified',
    'vip.expires': 'Expires',
    'vip.expiresIn': 'Expires in {days} days',
    'vip.benefits': 'Benefits',
    'vip.moreBenefits': '+{count} more benefits',
    'vip.regularMember': 'You\'re currently a regular member',
    'vip.contactSupport': 'Contact support to learn about VIP benefits',
    'vip.benefits': 'Benefits',
    'vip.prioritySupport': 'Priority customer support',
    'vip.reducedFees': 'Reduced withdrawal fees',
    'vip.higherLimits': 'Higher withdrawal limits',
    'vip.moreBenefitsText': '+{count} more benefits',
    'vip.level': 'VIP Level',
    'vip.membershipLevel': 'Membership Level',
    'vip.regular': 'Regular',
    'vip.currentlyRegularMember': 'You are currently a regular member',
    'vip.contactSupportForBenefits': 'Contact support to learn about VIP benefits',
    
    // About Us
    'about.title': 'About Us',
    'about.hero': 'Financial Platform',
    'about.subtitle': 'Empowering Your Financial Future',
    'about.mission': 'Our Mission',
    'about.missionText': 'We\'re dedicated to democratizing financial services and making them accessible to everyone, everywhere. Our platform combines cutting-edge technology with user-friendly design to provide secure, fast, and reliable financial solutions that empower individuals and businesses to achieve their financial goals.',
    'about.statistics': 'Platform Statistics',
    'about.activeUsers': 'Active Users',
    'about.transactions': 'Transactions',
    'about.countries': 'Countries',
    'about.contact': 'Contact Information',
    'about.emailSupport': 'Email Support',
    'about.phoneSupport': 'Phone Support',
    'about.copyright': '© 2024 Financial Platform. All rights reserved.',
    'about.licensed': 'Licensed and regulated financial services provider',
    
    // Bank Account
    'bank.yourAccounts': 'Your Bank Accounts',
    'bank.noAccounts': 'No bank accounts added yet',
    'bank.addAccount': 'Add Bank Account',
    'bank.addNew': 'Add New Bank Account',
    'bank.accountHolder': 'Account Holder Name',
    'bank.accountType': 'Account Type',
    'bank.checking': 'Checking',
    'bank.savings': 'Savings',
    'bank.mobile': 'Mobile Wallet',
    'bank.primary': 'Primary',
    'auth.createPassword': 'Create Password (6-22 digits)',
    'auth.numbersOnly': 'Numbers only (6-22 digits)',
    'auth.autoGenerated': 'Auto-generated',
    'auth.alreadyHaveAccount': 'Already have an account? Sign In',
    'auth.dontHaveAccount': "Don't have an account? Sign Up",
    'auth.signOut': 'Sign Out',
    'auth.incorrectPassword': 'Incorrect password',
    'auth.enterPassword': 'Enter your password',
    'auth.verifying': 'Verifying...',
    'auth.verify': 'Verify',
    'auth.verifyWithdrawalPassword': 'Verify Withdrawal Password',
    'auth.enterWithdrawalPasswordToProceed': 'Please enter your withdrawal password to proceed with withdrawal',
    'auth.withdrawalPassword': 'Withdrawal Password',
    'auth.enterWithdrawalPassword': 'Enter withdrawal password',
    'auth.loginPassword': 'Login Password',
    'auth.changePassword': 'Change Password',
    'auth.currentPassword': 'Current Password',
    'auth.enterCurrentPassword': 'Enter current password',
    'auth.newPassword': 'New Password (6-22 digits)',
    'auth.enterNewPassword': 'Enter new password',
    'auth.confirmNewPassword': 'Confirm New Password',
    'auth.confirmNewPasswordPlaceholder': 'Confirm new password',
    'auth.changeWithdrawalPassword': 'Change Withdrawal Password',
    'auth.currentWithdrawalPassword': 'Current Withdrawal Password',
    'auth.enterCurrentWithdrawalPassword': 'Enter current withdrawal password',
    'auth.newWithdrawalPassword': 'New Withdrawal Password (6-22 digits)',
    'auth.enterNewWithdrawalPassword': 'Enter new withdrawal password',
    'auth.confirmWithdrawalPassword': 'Confirm Withdrawal Password',
    'auth.confirmWithdrawalPasswordPlaceholder': 'Confirm withdrawal password',
    'auth.withdrawalPasswordInfo': 'Your withdrawal password is used to authorize withdrawal requests and should be kept secure.',
    'auth.setWithdrawalPassword': 'Set Withdrawal Password',
    'auth.setWithdrawalPasswordInfo': 'Set a secure withdrawal password that is different from your login password. This will be required for all withdrawal requests.',
    'auth.enterWithdrawalPasswordToProceed': 'Please enter your withdrawal password to proceed with withdrawal',
    'auth.noWithdrawalPasswordSet': 'No withdrawal password set. Please set one in your profile.',
    'auth.cancelar': 'Cancel',
    'auth.verificar': 'Verify',
    'auth.verifyWithdrawalPasswordTitle': 'Verify Withdrawal Password',
    'auth.pleaseEnterWithdrawalPassword': 'Please enter your withdrawal password to proceed with withdrawal',
    'auth.withdrawalPasswordLabel': 'Password',
    'auth.noWithdrawalPasswordSetMessage': 'No withdrawal password set. Please set one in your profile.',
    'orders.start': 'Start',
    'orders.complete': 'Complete',
    
    // Accounting Details
    'accounting.title': 'Accounting Details',
    'accounting.currentBalance': 'Current Balance',
    'accounting.lastUpdated': 'Last updated',
    'accounting.totalEarnings': 'Total Earnings',
    'accounting.totalWithdrawals': 'Total Withdrawals',
    'accounting.deposits': 'Deposits',
    'accounting.commissions': 'Commissions',
    'accounting.withdrawals': 'Withdrawals',
    'accounting.thisMonth': 'This Month',
    'accounting.netThisMonth': 'Net This Month',
    'accounting.accountSummary': 'Account Summary',
    'accounting.accountType': 'Account Type',
    'accounting.totalTransactions': 'Total Transactions',
    'accounting.netBalance': 'Net Balance',
    'accounting.currency': 'Currency',
    'accounting.country': 'Country',
    'accounting.realTimeSync': 'Real-time data sync enabled',
    
    // Deposit Records
    'depositRecords.title': 'Deposit Records',
    'depositRecords.totalDeposits': 'Total Deposits',
    'depositRecords.transactions': 'Transactions',
    'depositRecords.noDeposits': 'No Deposits Yet',
    'depositRecords.noDepositsDesc': 'Your deposit transactions will appear here',
    'depositRecords.completed': 'Completed',
    'depositRecords.paymentMethod': 'Payment Method',
    'depositRecords.referenceId': 'Reference ID',
    'depositRecords.notes': 'Notes',
    'depositRecords.invitationReward': 'invitation_reward',
    'depositRecords.invitationRewardFor': 'Invitation reward for user:',
    'depositRecords.realTimeUpdates': 'Real-time updates enabled',
    
    // Withdrawal Requests
    'withdrawalRequests.title': 'Withdrawal Requests',
    'withdrawalRequests.total': 'Total',
    'withdrawalRequests.completed': 'Completed',
    'withdrawalRequests.pending': 'Pending',
    'withdrawalRequests.noRequests': 'No Withdrawal Requests',
    'withdrawalRequests.noRequestsDesc': 'Your withdrawal requests will appear here',
    'withdrawalRequests.realTimeUpdates': 'Real-time status updates enabled',
    
    // Referral Modal
    'referral.title': 'Invite friends',
    'referral.totalInvitations': 'Total Invitations',
    'referral.totalEarned': 'Total Earned',
    'referral.pendingEarnings': 'Pending Earnings',
    'referral.pendingEarningsDesc': 'Will be credited once invited users complete their first order',
    'referral.yourReferralCode': 'Your Referral Code',
    'referral.referralLink': 'Referral Link',
    'referral.copyLink': 'Copy Link',
    'referral.share': 'Share',
    'referral.howItWorks': 'How Invitations Work',
    'referral.step1': 'Share your invitation code or link with friends',
    'referral.step2': 'They sign up using your invitation code (required for registration)',
    'referral.step3': 'You earn $10 when they complete their first order',
    'referral.recentInvitations': 'Recent Invitations',
    'referral.completed': 'completed',
    'referral.pending': 'pending',
    
    // Profile menu items
    'profile.accountingDetails': 'Accounting details',
    'profile.depositRecords': 'Deposit records',
    'profile.withdrawalRecords': 'Withdrawal records',
    'profile.aboutUs': 'About us',
    'profile.inviteFriends': 'Invite friends',
    'profile.signOut': 'Sign Out',
    
    // Navigation
    'nav.home': 'Home',
    'nav.grab': 'Grab',
    'nav.order': 'Order',
    'nav.profile': 'Profile',
    
    // Profile form
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.phoneNumber': 'Phone Number',
    'profile.accountInformation': 'Account Information',
    'profile.username': 'Username',
    'profile.country': 'Country',
    'profile.currency': 'Currency',
    'profile.vipStatus': 'VIP Status',
    'profile.vipMember': 'VIP Member',
    'profile.regularMember': 'Regular Member',
  },
  es: {
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.back': 'Atrás',
    'common.continue': 'Continuar',
    'common.submit': 'Enviar',
    'common.close': 'Cerrar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.confirm': 'Confirmar',
    'common.optional': 'Opcional',
    'common.required': 'Requerido',
    'common.yes': 'Sí',
    'common.no': 'No',
    
    // Navigation
    'nav.home': 'Hogar',
    'nav.grab': 'Agarrar',
    'nav.order': 'Orden',
    'nav.profile': 'Perfil',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido al mercado libre. Puedes participar en',
    'dashboard.portfolioBalance': 'El saldo de mi cartera',
    'dashboard.yesterday': 'Ayer',
    'dashboard.accumulated': 'Acumulado',
    'dashboard.today': 'Hoy',
    'dashboard.deposit': 'Depositar',
    'dashboard.withdrawal': 'Retirar',
    
    // Orders
    'orders.title': 'Lista de tareas',
    'orders.inProgress': 'Orden en progreso',
    'orders.completed': 'Completado',
    'orders.frozen': 'Congelado',
    'orders.currentBalance': 'Saldo Actual',
    'orders.orderValue': 'Valor del pedido:',
    'orders.commission': 'Comisión:',
    'orders.submitOrder': 'Enviar Orden',
    'orders.topUpRequired': 'Recarga Requerida',
    'orders.insufficientBalance': 'Saldo Insuficiente',
    'orders.needMoreFunds': 'Necesitas {amount} más para enviar esta orden.',
    'orders.orderAmount': 'Monto de la Orden:',
    'orders.requiredTopUp': 'Recarga Requerida:',
    'orders.addFunds': '¿Necesitas agregar fondos?',
    'orders.goToDeposit': 'Ir a Página de Depósito',
    'orders.orderCompleted': 'Orden Completada Exitosamente',
    'orders.orderCancelled': 'Orden Cancelada',
    'orders.noPendingOrders': 'No hay órdenes pendientes',
    'orders.noCompletedOrders': 'No hay órdenes completadas aún',
    'orders.noCancelledOrders': 'No hay órdenes canceladas',
    'orders.realTimeUpdates': 'Actualizaciones de órdenes en tiempo real',
    'orders.submitting': 'Enviando...',
    'orders.time': 'Hora:',
    'orders.orderCode': 'Código de orden:',
    'orders.nextOrder': 'Siguiente Orden',
    'orders.orderOf': 'Orden {current} de {total}',
    'orders.allOrdersCompleted': '¡Todas las órdenes completadas!',
    'orders.noOrdersAvailable': 'No hay órdenes disponibles',
    'orders.withdrawalLocked': 'Completa todas las órdenes para desbloquear retiros',
    'orders.withdrawalUnlocked': '¡Los retiros ya están disponibles!',
    'orders.firstOrderRequired': 'Completa tu primera orden para desbloquear retiros',
    'orders.orderProgress': 'Progreso de Órdenes',
    'orders.currentBalance': 'Saldo Actual',
    'orders.todaysIncome': 'Ingresos de hoy',
    'orders.completed': 'Completado',
    'orders.pending': 'Pendiente',
    'orders.ordersCompleted': 'Órdenes completadas',
    'orders.ordersPending': 'Órdenes pendientes',
    'orders.realTimeOrderUpdates': 'Actualizaciones de órdenes en tiempo real',
    'orders.noOrdersAvailable': 'No Hay Órdenes Disponibles',
    'orders.orderValue': 'Valor del pedido',
    'orders.commission': 'Comisión',
    'orders.entryLevelPackage': 'Paquete de nivel de entrada igual al saldo del usuario',
    'orders.realTimeBalance': 'En Vivo',
    'orders.previousBalance': 'Saldo Anterior',
    'orders.newBalance': 'Nuevo Saldo',
    
    // Profile
    'orders.ordersCompleted': 'Órdenes completadas',
    'orders.ordersPending': 'Órdenes pendientes',
    'orders.completeFirstOrderToUnlock': 'Completa tu primera orden para desbloquear retiros',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.balance': 'El saldo de mi cartera:',
    'profile.withdrawal': 'Retiro',
    'profile.accounting': 'Detalles contables',
    'profile.deposits': 'Registros de depósitos',
    'profile.withdrawals': 'Registros de retiros',
    'profile.about': 'Acerca de nosotros',
    'profile.invite': 'Invitar amigos',
    'profile.signOut': 'Cerrar Sesión',
    'profile.editProfile': 'Editar Perfil',
    'profile.changePassword': 'Cambiar Contraseña',
    'profile.bankAccount': 'Cuenta Bancaria',
    'profile.language': 'Idioma',
    'profile.accountInfo': 'Información de la Cuenta',
    'profile.username': 'Nombre de Usuario',
    'profile.country': 'País',
    'profile.currency': 'Moneda',
    'profile.vipStatus': 'Estado VIP',
    'profile.vipMember': 'Miembro VIP',
    'profile.regularMember': 'Miembro Regular',
    
    // Authentication
    'auth.signIn': 'Iniciar Sesión',
    'auth.signUp': 'Registrarse',
    'auth.createAccount': 'Crear Cuenta',
    'auth.welcomeBack': '¡Bienvenido de vuelta!',
    'auth.joinPlatform': 'Únete a nuestra plataforma financiera',
    'auth.phoneNumber': 'Número de Teléfono',
    'auth.password': 'Contraseña',
    'auth.firstName': 'Nombre',
    'auth.lastName': 'Apellido',
    'auth.inviteCode': 'Código de Invitación',
    'auth.processing': 'Procesando...',
    'auth.accountPreview': 'Vista Previa de la Cuenta',
    'auth.name': 'Nombre',
    'auth.quickRegistration': 'Registro Rápido',
    'auth.namesOptional': '¡Los nombres son opcionales y se generarán automáticamente si no se proporcionan!',
    'auth.inviteCodeRequired': 'Requerido: Ingresa el código de invitación de un amigo para crear tu cuenta',
    'auth.invalidInviteCode': 'Código de invitación inválido. Por favor verifica e intenta de nuevo.',
    'auth.validInviteCode': 'Código de invitación válido del usuario:',
    'auth.inviteRequired': 'Invitación Requerida',
    'auth.inviteRequiredDesc': '¡Necesitas un código de invitación válido de un usuario existente para unirte!',
    'auth.createAccountPrompt': '¿No tienes una cuenta? ¡Regístrate ahora!',
    
    // Deposit
    'deposit.title': 'Depositar Fondos',
    'deposit.currentBalance': 'Saldo Actual',
    'deposit.amount': 'Cantidad a Depositar',
    'deposit.selectBank': 'Seleccionar Banco',
    'deposit.accountName': 'Nombre de la Cuenta',
    'deposit.accountNumber': 'Número de Cuenta',
    'deposit.senderInfo': 'Información de Tu Cuenta',
    'deposit.uploadProof': 'Subir Comprobante de Transferencia',
    'deposit.submit': 'Enviar Solicitud de Depósito',
    'deposit.success': '¡Solicitud de Depósito Enviada!',
    'deposit.selectCountry': 'Seleccionar País',
    'deposit.transferToAccount': 'Transferir a esta cuenta',
    'deposit.bank': 'Banco',
    'deposit.chooseImage': 'Elegir Imagen',
    'deposit.removeImage': 'Eliminar Imagen',
    'deposit.uploadReceipt': 'Subir comprobante de transferencia',
    'deposit.depositAmount': 'Cantidad a Depositar',
    'deposit.currency': 'Moneda',
    'deposit.yourAccountInfo': 'Información de Tu Cuenta',
    'deposit.uploadTransferProof': 'Subir Comprobante de Transferencia',
    'deposit.uploadTransferReceipt': 'Subir comprobante de transferencia',
    'deposit.chooseImage': 'Elegir Imagen',
    'deposit.submitDepositRequest': 'Enviar Solicitud de Depósito',
    'deposit.selectCountry': 'Seleccionar País',
    'deposit.selectBank': 'Seleccionar Banco',
    'deposit.noBanksAvailable': 'No hay bancos disponibles para {country}',
    'deposit.currency': 'Moneda: {currency} ({symbol})',
    
    // Withdrawal
    'withdrawal.title': 'Retirar Fondos',
    'withdrawal.amount': 'Cantidad a Retirar',
    'withdrawal.method': 'Método de Retiro',
    'withdrawal.availableBalance': 'Saldo Disponible',
    'withdrawal.accountDetails': 'Detalles de la Cuenta',
    'withdrawal.minimumWithdrawal': 'Retiro mínimo',
    'withdrawal.verifyPassword': 'Verificar Contraseña',
    'withdrawal.enterPasswordToWithdraw': 'Por favor ingresa tu contraseña de inicio de sesión para proceder con el retiro',
    'withdrawal.withdrawalMethod': 'Método de Retiro',
    'withdrawal.addNewAccount': 'Agregar Nueva Cuenta',
    'withdrawal.selectFromSavedAccounts': 'Selecciona de tus cuentas guardadas:',
    'withdrawal.useSavedAccount': 'Usar Cuenta Guardada',
    'withdrawal.addNewAccount': 'Agregar Nueva Cuenta',
    'withdrawal.minimumWithdrawalAmount': 'Retiro mínimo: {symbol}10.00',
    'withdrawal.currency': 'Moneda: {currency}',
    'withdrawal.withdraw': 'Retirar {symbol}{amount}',
    'withdrawal.selectCountry': 'Seleccionar País',
    'withdrawal.selectBank': 'Seleccionar Banco',
    'withdrawal.noBanksAvailable': 'No hay bancos disponibles para {country}',
    'withdrawal.withdrawalAmount': 'Cantidad a Retirar ({currency})',
    'withdrawal.accountDetails': 'Detalles de la Cuenta',
    'withdrawal.accountHolderName': 'Nombre del Titular de la Cuenta',
    'withdrawal.accountNumber': 'Número de Cuenta',
    'withdrawal.minimumAmount': 'Mínimo: {symbol}10.00 | Moneda: {currency}',
    
    // Available Balance
    'withdrawal.availableBalance': 'Saldo Disponible',
    
    // General
    'general.save': 'Guardar',
    'general.cancel': 'Cancelar',
    'general.back': 'Atrás',
    'general.loading': 'Cargando...',
    'general.error': 'Error',
    'general.success': 'Éxito',
    'general.optional': 'Opcional',
    'general.required': 'Requerido',
    'general.continue': 'Continuar',
    
    // Additional translations for AuthForm
    'auth.createPassword': 'Crear Contraseña (6-22 dígitos)',
    'auth.numbersOnly': 'Solo números (6-22 dígitos)',
    'auth.autoGenerated': 'Auto-generado',
    'auth.alreadyHaveAccount': '¿Ya tienes una cuenta? Iniciar Sesión',
    'auth.dontHaveAccount': '¿No tienes una cuenta? Registrarse',
    'auth.signOut': 'Cerrar Sesión',
    'auth.incorrectPassword': 'Contraseña incorrecta',
    'auth.enterPassword': 'Ingresa tu contraseña',
    'auth.verifying': 'Verificando...',
    'auth.verify': 'Verificar',
    'auth.verifyWithdrawalPassword': 'Verificar Contraseña de Retiro',
    'auth.enterWithdrawalPasswordToProceed': 'Por favor ingresa tu contraseña de retiro para proceder con el retiro',
    'auth.withdrawalPassword': 'Contraseña',
    'auth.enterWithdrawalPassword': 'Ingresa contraseña de retiro',
    'auth.loginPassword': 'Contraseña de Inicio',
    'auth.changePassword': 'Cambiar Contraseña',
    'auth.currentPassword': 'Contraseña Actual',
    'auth.enterCurrentPassword': 'Ingresa contraseña actual',
    'auth.newPassword': 'Nueva Contraseña (6-22 dígitos)',
    'auth.enterNewPassword': 'Ingresa nueva contraseña',
    'auth.confirmNewPassword': 'Confirmar Nueva Contraseña',
    'auth.confirmNewPasswordPlaceholder': 'Confirma nueva contraseña',
    'auth.changeWithdrawalPassword': 'Cambiar Contraseña de Retiro',
    'auth.currentWithdrawalPassword': 'Contraseña de Retiro Actual',
    'auth.enterCurrentWithdrawalPassword': 'Ingresa contraseña de retiro actual',
    'auth.newWithdrawalPassword': 'Nueva Contraseña de Retiro (6-22 dígitos)',
    'auth.enterNewWithdrawalPassword': 'Ingresa nueva contraseña de retiro',
    'auth.confirmWithdrawalPassword': 'Confirmar Contraseña de Retiro',
    'auth.confirmWithdrawalPasswordPlaceholder': 'Confirma contraseña de retiro',
    'auth.withdrawalPasswordInfo': 'Tu contraseña de retiro se usa para autorizar solicitudes de retiro y debe mantenerse segura.',
    'auth.setWithdrawalPassword': 'Establecer Contraseña de Retiro',
    'auth.setWithdrawalPasswordInfo': 'Establece una contraseña de retiro segura que sea diferente de tu contraseña de inicio de sesión. Esto será requerido para todas las solicitudes de retiro.',
    'auth.enterWithdrawalPasswordToProceed': 'Por favor ingresa tu contraseña de retiro para proceder con el retiro',
    'auth.noWithdrawalPasswordSet': 'No se ha establecido contraseña de retiro. Por favor establece una en tu perfil.',
    'auth.cancelar': 'Cancelar',
    'auth.verificar': 'Verificar',
    'auth.verifyWithdrawalPasswordTitle': 'Verificar Contraseña de Retiro',
    'auth.pleaseEnterWithdrawalPassword': 'Por favor ingresa tu contraseña de retiro para proceder con el retiro',
    'auth.withdrawalPasswordLabel': 'Contraseña',
    'auth.noWithdrawalPasswordSetMessage': 'No se ha establecido contraseña de retiro. Por favor establece una en tu perfil.',
    
    // Accounting Details
    'accounting.title': 'Detalles Contables',
    'accounting.currentBalance': 'Saldo Actual',
    'accounting.lastUpdated': 'Última actualización',
    'accounting.totalEarnings': 'Ganancias Totales',
    'accounting.totalWithdrawals': 'Retiros Totales',
    'accounting.deposits': 'Depósitos',
    'accounting.commissions': 'Comisiones',
    'accounting.withdrawals': 'Retiros',
    'accounting.thisMonth': 'Este Mes',
    'accounting.netThisMonth': 'Neto Este Mes',
    'accounting.accountSummary': 'Resumen de Cuenta',
    'accounting.accountType': 'Tipo de Cuenta',
    'accounting.totalTransactions': 'Transacciones Totales',
    'accounting.netBalance': 'Saldo Neto',
    'accounting.currency': 'Moneda',
    'accounting.country': 'País',
    'accounting.realTimeSync': 'Sincronización de datos en tiempo real habilitada',
    
    // Deposit Records
    'depositRecords.title': 'Registros de Depósitos',
    'depositRecords.totalDeposits': 'Depósitos Totales',
    'depositRecords.transactions': 'Transacciones',
    'depositRecords.noDeposits': 'No Hay Depósitos Aún',
    'depositRecords.noDepositsDesc': 'Tus transacciones de depósito aparecerán aquí',
    'depositRecords.completed': 'Completado',
    'depositRecords.paymentMethod': 'Método de Pago',
    'depositRecords.referenceId': 'ID de Referencia',
    'depositRecords.notes': 'Notas',
    'depositRecords.invitationReward': 'recompensa_invitacion',
    'depositRecords.invitationRewardFor': 'Recompensa de invitación para usuario:',
    'depositRecords.realTimeUpdates': 'Actualizaciones en tiempo real habilitadas',
    
    // Withdrawal Requests
    'withdrawalRequests.title': 'Solicitudes de Retiro',
    'withdrawalRequests.total': 'Total',
    'withdrawalRequests.completed': 'Completado',
    'withdrawalRequests.pending': 'Pendiente',
    'withdrawalRequests.noRequests': 'No Hay Solicitudes de Retiro',
    'withdrawalRequests.noRequestsDesc': 'Tus solicitudes de retiro aparecerán aquí',
    'withdrawalRequests.realTimeUpdates': 'Actualizaciones de estado en tiempo real habilitadas',
    
    // Referral Modal
    'referral.title': 'Invitar amigos',
    'referral.totalInvitations': 'Invitaciones Totales',
    'referral.totalEarned': 'Total Ganado',
    'referral.pendingEarnings': 'Ganancias Pendientes',
    'referral.pendingEarningsDesc': 'Se acreditarán una vez que los usuarios invitados completen su primera orden',
    'referral.yourReferralCode': 'Tu Código de Referencia',
    'referral.referralLink': 'Enlace de Referencia',
    'referral.copyLink': 'Copiar Enlace',
    'referral.share': 'Compartir',
    'referral.howItWorks': 'Cómo Funcionan las Invitaciones',
    'referral.step1': 'Comparte tu código de invitación o enlace con amigos',
    'referral.step2': 'Se registran usando tu código de invitación (requerido para el registro)',
    'referral.step3': 'Ganas $10 cuando completan su primera orden',
    'referral.recentInvitations': 'Invitaciones Recientes',
    'referral.completed': 'completado',
    'referral.pending': 'pendiente',
    
    // Additional translations for About page
    'about.bankSecurity': 'Seguridad de Nivel Bancario',
    'about.bankSecurityDesc': 'Tus fondos y datos están protegidos con encriptación y protocolos de seguridad de nivel empresarial.',
    'about.lightningFast': 'Súper Rápido',
    'about.lightningFastDesc': 'Depósitos y retiros instantáneos con actualizaciones de saldo en tiempo real en todos los dispositivos.',
    'about.globalCommunity': 'Comunidad Global',
    'about.globalCommunityDesc': 'Únete a millones de usuarios en todo el mundo que confían en nuestra plataforma para sus necesidades financieras.',
    'about.support247': 'Soporte 24/7',
    'about.support247Desc': 'Nuestro equipo de soporte dedicado siempre está aquí para ayudarte con cualquier pregunta o inquietud.',
    
    // Additional translations for Orders
    'orders.start': 'Inicio',
    'orders.complete': 'Completar',
    
    // Profile menu items
    'profile.accountingDetails': 'Detalles contables',
    'profile.depositRecords': 'Registros de depósitos',
    'profile.withdrawalRecords': 'Registros de retiros',
    'profile.aboutUs': 'Acerca de nosotros',
    'profile.inviteFriends': 'Invitar amigos',
    'profile.signOut': 'Cerrar Sesión',
    
    // Navigation
    'nav.home': 'Inicio',
    'nav.grab': 'Agarrar',
    'nav.order': 'Orden',
    'nav.profile': 'Perfil',
    
    // Profile form
    'profile.firstName': 'Nombre',
    'profile.lastName': 'Apellido',
    'profile.phoneNumber': 'Número de Teléfono',
    'profile.accountInformation': 'Información de la Cuenta',
    'profile.username': 'Nombre de Usuario',
    'profile.country': 'País',
    'profile.currency': 'Moneda',
    'profile.vipStatus': 'Estado VIP',
    'profile.vipMember': 'Miembro VIP',
    'profile.regularMember': 'Miembro Regular',
    
    // Hall of Fame
    'hallOfFame.title': 'Salón de la Fama',
    'hallOfFame.liveUpdates': 'Actualizaciones en Vivo',
    
    // VIP Status
    'vip.status': 'Estado VIP',
    'vip.membershipLevel': 'Nivel de Membresía',
    'vip.live': 'En Vivo',
    'vip.verified': 'Verificado',
    'vip.expires': 'Expira',
    'vip.expiresIn': 'Expira en {days} días',
    'vip.benefits': 'Beneficios',
    'vip.moreBenefits': '+{count} beneficios más',
    'vip.regularMember': 'Actualmente eres un miembro regular',
    'vip.contactSupport': 'Contacta al soporte para conocer los beneficios VIP',
    'vip.benefits': 'Beneficios',
    'vip.prioritySupport': 'Soporte prioritario al cliente',
    'vip.reducedFees': 'Tarifas de retiro reducidas',
    'vip.higherLimits': 'Límites de retiro más altos',
    'vip.moreBenefitsText': '+{count} beneficios más',
    'vip.level': 'Nivel VIP',
    'vip.membershipLevel': 'Nivel de Membresía',
    'vip.regular': 'Regular',
    'vip.currentlyRegularMember': 'Actualmente eres un miembro regular',
    'vip.contactSupportForBenefits': 'Contacta al soporte para conocer los beneficios VIP',
    'vip.exclusivePromotions': 'Promociones exclusivas',
    'vip.personalManager': 'Gerente de cuenta personal',
    'vip.advancedTools': 'Herramientas de trading avanzadas',
    'vip.premiumInvestments': 'Oportunidades de inversión premium',
    'vip.vipEvents': 'Acceso a eventos VIP',
    'vip.customStrategies': 'Estrategias de trading personalizadas',
    'vip.exclusivePromotions': 'Exclusive promotions',
    'vip.personalManager': 'Personal account manager',
    'vip.advancedTools': 'Advanced trading tools',
    'vip.premiumInvestments': 'Premium investment opportunities',
    'vip.vipEvents': 'VIP events access',
    'vip.customStrategies': 'Custom trading strategies',
    
    // About Us
    'about.title': 'Acerca de Nosotros',
    'about.hero': 'Plataforma Financiera',
    'about.subtitle': 'Potenciando Tu Futuro Financiero',
    'about.mission': 'Nuestra Misión',
    'about.missionText': 'Estamos dedicados a democratizar los servicios financieros y hacerlos accesibles para todos, en todas partes. Nuestra plataforma combina tecnología de vanguardia con un diseño fácil de usar para proporcionar soluciones financieras seguras, rápidas y confiables que empoderan a individuos y empresas para lograr sus objetivos financieros.',
    'about.statistics': 'Estadísticas de la Plataforma',
    'about.activeUsers': 'Usuarios Activos',
    'about.transactions': 'Transacciones',
    'about.countries': 'Países',
    'about.contact': 'Información de Contacto',
    'about.emailSupport': 'Soporte por Email',
    'about.phoneSupport': 'Soporte Telefónico',
    'about.copyright': '© 2024 Plataforma Financiera. Todos los derechos reservados.',
    'about.licensed': 'Proveedor de servicios financieros licenciado y regulado',
    
    // Bank Account
    'bank.yourAccounts': 'Tus Cuentas Bancarias',
    'bank.noAccounts': 'No se han agregado cuentas bancarias aún',
    'bank.addAccount': 'Agregar Cuenta Bancaria',
    'bank.addNew': 'Agregar Nueva Cuenta Bancaria',
    'bank.accountHolder': 'Nombre del Titular de la Cuenta',
    'bank.accountType': 'Tipo de Cuenta',
    'bank.checking': 'Corriente',
    'bank.savings': 'Ahorros',
    'bank.mobile': 'Billetera Móvil',
    'bank.primary': 'Principal',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'es'>('en');

  const initializeLanguage = useCallback(() => {
    const savedLanguage = localStorage.getItem('language') as 'en' | 'es';
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'es')) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    initializeLanguage();
  }, [initializeLanguage]);

  const handleSetLanguage = useCallback((lang: 'en' | 'es') => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    // Force re-render of all components by updating the context
    window.dispatchEvent(new CustomEvent('languageChanged', { detail: { language: lang } }));
  }, []);

  const t = useCallback((key: string, params?: { [key: string]: string | number }): string => {
    let translation = translations[language][key as keyof typeof translations['en']] || key;
    
    // Handle parameter substitution
    if (params) {
      Object.keys(params).forEach(paramKey => {
        translation = translation.replace(`{${paramKey}}`, String(params[paramKey]));
      });
    }
    
    return translation;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};